# Generated by Django 3.2.4 on 2024-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('focus_plant_name', models.CharField(max_length=255)),
                ('focus_plant_image', models.ImageField(default='default_image', upload_to='images/')),
                ('environment', models.TextField()),
                ('culinary_uses', models.TextField()),
                ('medicinal_uses', models.TextField()),
                ('folklore', models.TextField(blank=True)),
                ('lookalike_plant_name', models.CharField(max_length=255)),
                ('lookalike_plant_image', models.ImageField(default='default_lookalike', upload_to='images/')),
            ],
        ),
    ]
