# Generated by Django 3.2.4 on 2024-02-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_in_focus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantinfocus',
            old_name='focus_plant_name',
            new_name='featured_item',
        ),
        migrations.RenameField(
            model_name='plantinfocus',
            old_name='focus_plant_image',
            new_name='featured_item_image',
        ),
        migrations.RenameField(
            model_name='plantinfocus',
            old_name='lookalike_plant_name',
            new_name='lookalike_item',
        ),
        migrations.RenameField(
            model_name='plantinfocus',
            old_name='lookalike_plant_image',
            new_name='lookalike_item_image',
        ),
    ]
