# Generated by Django 3.2.4 on 2024-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_in_focus', '0002_auto_20240201_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfocus',
            name='folklore',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plantinfocus',
            name='lookalike_item',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plantinfocus',
            name='lookalike_item_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
