# Generated by Django 3.2.4 on 2024-02-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_in_focus', '0003_auto_20240202_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfocus',
            name='lookalike_item',
        ),
        migrations.RemoveField(
            model_name='plantinfocus',
            name='lookalike_item_image',
        ),
        migrations.AlterField(
            model_name='plantinfocus',
            name='featured_item_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
