# Generated by Django 3.2.4 on 2024-01-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20240130_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('', 'Select Duration'), ('Half Day', 'Half Day'), ('Full Day', 'Full Day')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
    ]
